<div class="addObject-container hidden" id="addObject-container">
	<h3>Add new point of interest</h3>
	<br>
	<form role="form" method="POST" id="addObject-form"
		onsubmit="mapObject.submitCreateForm(this); return false;">
		<div class="form-group">
			<label for="name" class="col-sm-4 control-label">Name </label>
    		<div class="col-sm-8">
			<input type="text" class="form-control" name="name"/>
			</div>
		</div>
		</br>
		<div class="form-group">
			<label for="description" class="col-sm-4 control-label">Description </label>
    		<div class="col-sm-8">
			<input type="text" class="form-control" name="description"/>
			</div>
		</div>
	</form>
	<hr>
	<button type="button" class="btn btn-primary"
		onclick="$('#addObject-form').submit()">Save</button>
</div>