<div id="iw-container" data-objectId="1">
	<div class="iw-title">m.name</div>
	<div class="iw-content">
		<div class="iw-subTitle">Description</div>
		<div class="sprite lodging-2" data-toggle="tooltip" title="Hotel"></div>
		<p>m.description</p>
		<div class="iw-subTitle">Coordinates</div>
		<p></p>
		<div class="iw-subTitle">Filters</div>
		<a href="#" id="filter-type" data-type="1">Others of type</a>
		<a href="#" id="filter-nearest">Nearest 5</a>
		<a href="#" id="filter-like">Others Like</a>
		<hr>
		<div id="iw-filter-result"></div>
	</div>
	<div class="iw-bottom-gradient"></div>
</div>