<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed"
				data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
				aria-expanded="false">
				<span class="sr-only">Toggle navigation</span> <span
					class="icon-bar"></span> <span class="icon-bar"></span> <span
					class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#">MongoPlaces</a>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse"
			id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li id="home"><a href="../public">Home <span class="sr-only">(current)</span></a></li>
				<li id="mapList"><a href="mapList">List View <span class="sr-only"></span></a></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<?php if (hasLoggedIn()): ?>
				<li class="dropdown">
				<a href="#"	class="dropdown-toggle" data-toggle="dropdown" role="button"
					aria-haspopup="true" aria-expanded="false">Hello, <?php echo getUsername(); ?> <span
						class="caret"></span></a>
					<ul class="dropdown-menu">
						<li><a href="readFavourites">My Favourites</a></li>
						<li><a href="myPlaces">My places</a></li>
						<li role="separator" class="divider"></li>
						<li><a href="logout">Logout</a></li>
					</ul></li>
				<?php else : ?>
				<li><a href="#" data-toggle="modal" data-toggle="tooltip" title="Login!" data-target="#login-modal">Hello, <u><?php echo getUsername(); ?></u></a></li>
				<?php endif; ?>
			</ul>
		</div>
		<!-- /.navbar-collapse -->
	</div>
	<!-- /.container-fluid -->
</nav>
