<?php
use Framework\Support\View;
?>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, user-scalable=yes" />

		<link rel="shortcut icon" href="favicon.ico" type="image/png" />
		<link rel="stylesheet" type="text/css" href="assets/css/main.css" />

		<!-- Bootstrap -->
		<link rel="stylesheet" href="assets/css/bootstrap.min.css">

		<!-- JS -->
		<!-- JQuery -->
		<script src="https://code.jquery.com/jquery.js"></script>
		<link href="https://code.jquery.com/ui/1.11.2/themes/blitzer/jquery-ui.css" rel="stylesheet" type="text/css" />
		<script src="https://code.jquery.com/ui/1.11.2/jquery-ui.min.js"></script>
		
		<!-- Bootstrap -->
		<script src="assets/js/bootstrap.min.js"></script>
		<script src="assets/js/main.js"></script>
		<script	src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDc47RjNB3TfzRBnym7-C59ndTvxyRD664"></script>
	</head>
	<body>
		<?php echo View::partial('partial._userBar'); ?>
		<?php echo View::partial('partial._login'); ?>
	<div class="container-fluid">
		<div id="map"></div>
	</div>
</body>
</html>
